# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

normalizeVector <- function(v) {
    .Call('GeLaToLab_normalizeVector', PACKAGE = 'GeLaToLab', v)
}

evaluateLQ <- function(d, g) {
    .Call('GeLaToLab_evaluateLQ', PACKAGE = 'GeLaToLab', d, g)
}

evaluateMQ <- function(d, g) {
    .Call('GeLaToLab_evaluateMQ', PACKAGE = 'GeLaToLab', d, g)
}

computeRandomNeighbor <- function(group, columns, k) {
    .Call('GeLaToLab_computeRandomNeighbor', PACKAGE = 'GeLaToLab', group, columns, k)
}

computeRandomNeighbors <- function(group, columns, k, n) {
    .Call('GeLaToLab_computeRandomNeighbors', PACKAGE = 'GeLaToLab', group, columns, k, n)
}

collectNondominated <- function(pop, arch) {
    .Call('GeLaToLab_collectNondominated', PACKAGE = 'GeLaToLab', pop, arch)
}

